import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Rethink_Sans } from "next/font/google";
import localFont from "next/font/local";
import Script from "next/script";
import { auth } from "~/auth";
import OneTapComponent from "~/components/googleOneTap";
import { Debug } from "~/components/ui/debug";
import { cn } from "~/lib/utils";
import "./globals.css";
import "./prose-mirror.css";

const inter = Rethink_Sans({
  subsets: ["latin"],
  display: "swap",
  fallback: ["Arial", "sans-serif"],
  adjustFontFallback: true,
});
const calSans = localFont({
  src: "../../assets/fonts/CalSans-SemiBold.woff2",
  variable: "--font-cal",
});
export const metadata: Metadata = {
  title: "Trekyaari",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body
          className={cn(
            inter.className,
            calSans.variable,
            "antialiased relative"
          )}
        >
          {children}
          <Debug />

          <OneTapComponent />
          <Toaster />
          <Script
            src="https://accounts.google.com/gsi/client"
            strategy="beforeInteractive"
          />
        </body>
      </html>
    </SessionProvider>
  );
}
